# Generated by Django 4.1.5 on 2023-01-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=350)),
                ('first_name', models.CharField(default='', max_length=350)),
                ('last_name', models.CharField(default='', max_length=350)),
                ('verify_code', models.CharField(blank=True, default='', max_length=70)),
                ('verify_token', models.CharField(blank=True, default='', max_length=70)),
            ],
        ),
    ]
