# Generated by Django 4.1.5 on 2023-01-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0004_list_workspace_relationship_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship_tables',
            name='role',
            field=models.CharField(default='', max_length=350),
        ),
    ]
