# Generated by Django 4.1.5 on 2023-01-31 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0005_relationship_tables_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship_tables',
            old_name='user_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='relationship_tables',
            old_name='list_id',
            new_name='list',
        ),
        migrations.RenameField(
            model_name='relationship_tables',
            old_name='workspace_id',
            new_name='workspace',
        ),
    ]
