# Generated by Django 4.1.5 on 2023-02-01 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0006_rename_user_id_relationship_tables_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=350)),
                ('frequency', models.CharField(default='', max_length=350)),
                ('attachments', models.CharField(default='', max_length=350)),
                ('dute_date', models.DateField(default='', null=True)),
                ('description', models.CharField(default='', max_length=350)),
            ],
        ),
        migrations.AddField(
            model_name='relationship_tables',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='taskApp.task'),
        ),
    ]
