# Generated by Django 4.1.5 on 2023-02-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0007_task_relationship_tables_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(default='', max_length=350),
        ),
    ]
