# Generated by Django 4.1.5 on 2023-02-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0010_alter_task_check_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='check_status',
        ),
        migrations.AddField(
            model_name='relationship_tables',
            name='check_status',
            field=models.BooleanField(default=0),
        ),
    ]
