# Generated by Django 4.1.5 on 2023-02-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0011_remove_task_check_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship_tables',
            name='task_progress',
            field=models.CharField(default='', max_length=350),
        ),
    ]
