# Generated by Django 4.1.5 on 2023-02-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0013_rename_task_progress_relationship_tables_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(blank=True, default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='relationship_tables',
            name='priority',
            field=models.CharField(blank=True, default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='relationship_tables',
            name='role',
            field=models.CharField(blank=True, default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='task',
            name='attachments',
            field=models.CharField(blank=True, default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='task',
            name='frequency',
            field=models.CharField(blank=True, default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(blank=True, default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='email',
            field=models.CharField(blank=True, default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='name',
            field=models.CharField(blank=True, default='', max_length=350),
        ),
    ]
